# Regenerate docs/cases/CASE_REGISTRY.md from flat case files, and project each case's
# body "## Run State" into queryable YAML frontmatter (run_status, tier, app, tags, ...).
#
# Two passes:
#   1. Frontmatter projection (default ON; -SkipFrontmatter to disable). For every real case file
#      (nex-/tab-/prn-/plt-/infra- prefix) it parses the "## Run State" body block and writes a
#      GENERATED frontmatter block. The body stays the source of truth; frontmatter is derived,
#      so Dataview/Bases/tags can query it without manual duplication. Operator-authored keys
#      (status, last_reviewed, scope) are preserved untouched. Idempotent: re-runs produce no diff.
#   2. Registry generation (non-destructive): rebuilds CASE_REGISTRY.md as a summarized,
#      status-annotated wikilink index. Full case files remain the durable audit trail.
#
# Source is ASCII-only (PowerShell 5.1 safe); emoji are built from codepoints for the output file.
# Usage: .\scripts\obsidian-case-registry.ps1            (registry + frontmatter)
#        .\scripts\obsidian-case-registry.ps1 -SkipFrontmatter   (registry only)

param(
    [string]$VaultPath = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [switch]$SkipFrontmatter
)

$ErrorActionPreference = "Stop"

# Anchored leading-token status classifier (shared lib; also used by the
# recurrence-check gate). Keeps status classification in one place.
. (Join-Path $PSScriptRoot "lib\case-status-classify.ps1")

$casesDir = Join-Path $VaultPath "docs\cases"
$skip = @('CASE_INDEX', 'CONTRACTS_HUB', 'OPERATOR_HOME', 'OPS_KANBAN', 'CASE_REGISTRY', 'CASE_DASHBOARD', '_TEMPLATE')

# Keys this script owns in frontmatter. Everything else (status, last_reviewed, scope, ...) is
# operator-authored and preserved verbatim.
$GeneratedKeys = @('run_status', 'tier', 'app', 'next_agent', 'branch', 'interrupted', 'updated', 'tags')
$FenceComment  = '# --- generated by obsidian-case-registry.ps1 (do not edit; derived from ## Run State) ---'

# Output glyphs (built from codepoints so the script source stays pure ASCII)
$EmOk    = [char]::ConvertFromUtf32(0x2705)   # check mark
$EmActive= [char]::ConvertFromUtf32(0x1F7E1)  # yellow circle
$EmBlock = [char]::ConvertFromUtf32(0x26D4)   # no entry
$Sep     = [char]::ConvertFromUtf32(0x00B7)   # middle dot
$Ell     = [char]::ConvertFromUtf32(0x2026)   # ellipsis

function Get-AppFromSlug {
    param([string]$Slug)
    if ($Slug -match '^nex-')   { return 'nexus' }
    if ($Slug -match '^tab-')   { return 'tablet' }
    if ($Slug -match '^prn-')   { return 'print' }
    if ($Slug -match '^plt-')   { return 'platform' }
    if ($Slug -match '^infra-') { return 'infra' }
    return $null
}

# Pull a single "- key: value" line out of the body, stripping inline HTML comments.
function Get-RunStateValue {
    param([string[]]$Lines, [string]$Key)
    foreach ($l in $Lines) {
        if ($l -match ('^\s*-\s*' + [regex]::Escape($Key) + ':\s*(.+)$')) {
            $v = $Matches[1] -replace '<!--.*?-->', ''
            return $v.Trim()
        }
    }
    return $null
}

function Get-CaseSummary {
    param([string]$Path)

    $raw = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    if (-not $raw) { return $null }
    $lines = $raw -split "`r?`n"

    $hasRunState = $false
    foreach ($l in $lines) { if ($l -match '^##\s+Run State') { $hasRunState = $true; break } }

    # --- Run State fields (body is source of truth) ---
    $statusRaw = Get-RunStateValue -Lines $lines -Key 'status'
    $status = if ($statusRaw) { $statusRaw } else { '-' }

    $updatedRaw = Get-RunStateValue -Lines $lines -Key 'updated'
    $updated = if ($updatedRaw) { ($updatedRaw -split '\s+')[0] } else { '-' }

    # Normalize run_status to the canonical enum via the anchored leading-token
    # classifier, so a verbose "IN_PROGRESS (... complete ...)" is never read as
    # COMPLETE. Returns $null if the leading token is not one of the three.
    $runStatus = Get-CaseStatusToken $status

    $tierRaw = Get-RunStateValue -Lines $lines -Key 'tier'
    $tier = if ($tierRaw -and $tierRaw -match '^[123]$') { [int]$tierRaw } else { $null }

    $branch = Get-RunStateValue -Lines $lines -Key 'branch'
    if ($branch -and $branch -match '[<|>]') { $branch = $null }   # unfilled template placeholder

    $nextAgent = Get-RunStateValue -Lines $lines -Key 'next_agent'
    if ($nextAgent -and $nextAgent -match '\|') { $nextAgent = $null }   # unfilled placeholder

    $interruptedRaw = Get-RunStateValue -Lines $lines -Key 'interrupted'
    $interrupted = $null
    if ($interruptedRaw -match '^true$')  { $interrupted = $true }
    elseif ($interruptedRaw -match '^false$') { $interrupted = $false }

    $appRaw = Get-RunStateValue -Lines $lines -Key 'app'
    $appOverride = $null
    $ValidApps = @('nexus', 'tablet', 'print', 'platform', 'infra', 'other')
    if ($appRaw) {
        if ($ValidApps -contains $appRaw) { $appOverride = $appRaw }
        else { Write-Warning "Unknown app override '$appRaw' in $Path; ignoring." }
    }

    # --- Summary line for the registry table ---
    # Skip the leading YAML frontmatter so its generated fence comment ("# ---")
    # is not mistaken for the markdown H1 title (which would make the summary read
    # the next frontmatter key, e.g. "app: infra").
    $bodyStart = 0
    if ($lines.Count -gt 0 -and $lines[0].Trim() -eq '---') {
        for ($i = 1; $i -lt $lines.Count; $i++) {
            if ($lines[$i].Trim() -eq '---') { $bodyStart = $i + 1; break }
        }
    }

    $summary = ''
    $titleIdx = -1
    for ($i = $bodyStart; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^#\s+') { $titleIdx = $i; break }
    }
    if ($titleIdx -ge 0) {
        $end = [Math]::Min($titleIdx + 6, $lines.Count)
        for ($i = $titleIdx + 1; $i -lt $end; $i++) {
            $t = $lines[$i].Trim()
            if ($t -eq '' -or $t -match '^<!--' -or $t -match '^#' -or $t -match '^-\s') { continue }
            $summary = $t; break
        }
    }
    if (-not $summary) {
        $pIdx = -1
        for ($i = 0; $i -lt $lines.Count; $i++) { if ($lines[$i] -match '^##\s+Problem') { $pIdx = $i; break } }
        if ($pIdx -ge 0) {
            $end = [Math]::Min($pIdx + 8, $lines.Count)
            for ($i = $pIdx + 1; $i -lt $end; $i++) {
                $t = $lines[$i].Trim()
                if ($t -eq '' -or $t -match '^<!--') { continue }
                $summary = $t; break
            }
        }
    }
    $summary = $summary -replace '\|', '/' -replace '`', ''
    if ($summary.Length -gt 120) { $summary = $summary.Substring(0, 117).TrimEnd() + $Ell }

    return [pscustomobject]@{
        Status = $status; Updated = $updated; Summary = $summary
        RunStatus = $runStatus; Tier = $tier; Branch = $branch
        NextAgent = $nextAgent; Interrupted = $interrupted
        AppOverride = $appOverride; HasRunState = $hasRunState
    }
}

# Quote a YAML scalar only if it needs it (colon, hash, leading special char).
function Format-YamlScalar {
    param([string]$Value)
    if ($Value -match "[:#\[\]{}&*!|>'""%@`` ]" ) {
        return "'" + ($Value -replace "'", "''") + "'"
    }
    return $Value
}

# Write the derived frontmatter block into a case file. Returns 'changed' | 'unchanged' | 'skipped'.
function Update-CaseFrontmatter {
    param([string]$Path, [string]$Slug, $Summary)

    # Real case prefix -> known app; otherwise project as 'other' only if it has a Run State
    # (a genuine work item), so unprefixed cases like kds-implementation-plan stay queryable.
    # Pure reference/audit notes with no Run State are left untouched.
    $app = Get-AppFromSlug -Slug $Slug
    if (-not $app -and $Summary.AppOverride) { $app = $Summary.AppOverride }
    if (-not $app) {
        if ($Summary.HasRunState) { $app = 'other' } else { return 'skipped' }
    }

    $raw = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    $nl = if ($raw -match "`r`n") { "`r`n" } else { "`n" }

    # Match the leading YAML frontmatter block.
    $m = [regex]::Match($raw, '^---\r?\n(.*?)\r?\n---\r?\n', [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if (-not $m.Success) {
        Write-Warning "No frontmatter in $Slug; skipping projection."
        return 'skipped'
    }

    $fmBody = $m.Groups[1].Value
    $fmLines = $fmBody -split "`r?`n"

    # Keep operator-authored lines; drop any prior generated keys + fence comment.
    $operatorLines = @()
    foreach ($l in $fmLines) {
        if ($l.Trim() -eq $FenceComment.Trim()) { continue }
        $isGenerated = $false
        foreach ($k in $GeneratedKeys) {
            if ($l -match ('^\s*' + [regex]::Escape($k) + '\s*:')) { $isGenerated = $true; break }
        }
        if (-not $isGenerated) { $operatorLines += $l }
    }

    # Build the generated block (only keys with values).
    $tags = @("app/$app")
    if ($Summary.RunStatus) { $tags += "status/" + $Summary.RunStatus.ToLower().Replace('_','-') }
    if ($null -ne $Summary.Tier) { $tags += "tier/$($Summary.Tier)" }

    $genLines = @($FenceComment)
    $genLines += "app: $app"
    if ($Summary.RunStatus)      { $genLines += "run_status: $($Summary.RunStatus)" }
    if ($null -ne $Summary.Tier) { $genLines += "tier: $($Summary.Tier)" }
    if ($Summary.NextAgent)      { $genLines += "next_agent: $(Format-YamlScalar $Summary.NextAgent)" }
    if ($Summary.Branch)         { $genLines += "branch: $(Format-YamlScalar $Summary.Branch)" }
    if ($null -ne $Summary.Interrupted) { $genLines += "interrupted: $($Summary.Interrupted.ToString().ToLower())" }
    if ($Summary.Updated -and $Summary.Updated -ne '-') { $genLines += "updated: $($Summary.Updated)" }
    $genLines += "tags: [" + (($tags | Sort-Object -Unique) -join ', ') + "]"

    $newFmLines = @($operatorLines | Where-Object { $_ -ne '' }) + $genLines
    $newFm = ($newFmLines -join $nl)

    $rest = $raw.Substring($m.Length)
    $newRaw = "---" + $nl + $newFm + $nl + "---" + $nl + $rest

    if ($newRaw -eq $raw) { return 'unchanged' }

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $newRaw, $utf8NoBom)
    return 'changed'
}

$groups = [ordered]@{
    'nex-case' = @(); 'tab-case' = @(); 'prn-case' = @()
    'plt-case' = @(); 'infra-case' = @(); 'infra-' = @(); 'other' = @()
}

$fmChanged = 0; $fmUnchanged = 0; $fmSkipped = 0

Get-ChildItem -Path $casesDir -Filter '*.md' | Sort-Object Name | ForEach-Object {
    $b = $_.BaseName
    if ($skip -contains $b) { return }
    if ($b -match '^nex-case-') { $key = 'nex-case' }
    elseif ($b -match '^tab-case-') { $key = 'tab-case' }
    elseif ($b -match '^prn-') { $key = 'prn-case' }
    elseif ($b -match '^plt-case-') { $key = 'plt-case' }
    elseif ($b -match '^infra-case-') { $key = 'infra-case' }
    elseif ($b -match '^infra-') { $key = 'infra-' }
    else { $key = 'other' }
    $s = Get-CaseSummary -Path $_.FullName

    if (-not $SkipFrontmatter) {
        switch (Update-CaseFrontmatter -Path $_.FullName -Slug $b -Summary $s) {
            'changed'   { $fmChanged++ }
            'unchanged' { $fmUnchanged++ }
            'skipped'   { $fmSkipped++ }
        }
    }

    $groups[$key] += [pscustomobject]@{ Slug = $b; Status = $s.Status; Updated = $s.Updated; Summary = $s.Summary }
}

function Format-Status {
    param([string]$s)
    switch (Get-CaseStatusToken $s) {
        'COMPLETE'    { return "$EmOk COMPLETE" }
        'IN_PROGRESS' { return "$EmActive IN_PROGRESS" }
        'BLOCKED'     { return "$EmBlock BLOCKED" }
    }
    return $s
}

$titles = @{
    'nex-case' = 'Nexus (`nex-case-*`)'; 'tab-case' = 'Tablet (`tab-case-*`)'
    'prn-case' = 'Print bridge (`prn-*`)'; 'plt-case' = 'Platform (`plt-case-*`)'
    'infra-case' = 'Infra numbered (`infra-case-*`)'; 'infra-' = 'Infra other (`infra-*`)'
    'other' = 'Other / intake / audits'
}

$all = $groups.Values | ForEach-Object { $_ }
$total = ($all | Measure-Object).Count
$complete = ($all | Where-Object { (Get-CaseStatusToken $_.Status) -eq 'COMPLETE' } | Measure-Object).Count
$active = ($all | Where-Object { (Get-CaseStatusToken $_.Status) -in @('IN_PROGRESS', 'BLOCKED') } | Measure-Object).Count

$intro = "**$total cases** $Sep $complete complete $Sep $active active/blocked. Auto-generated summary of every case file in docs/cases/; full files remain the durable audit trail (see RESUME_PROTOCOL). Regenerate: scripts/obsidian-case-registry.ps1."
$hub = "Hub: [[OPERATOR_HOME]] $Sep Dashboard: [[CASE_DASHBOARD]] $Sep Bases: [[CASES.base|CASES.base]] $Sep Index: [[CASE_INDEX]] $Sep Contracts: [[CONTRACTS_HUB]] $Sep Vault: [[VAULT_INDEX]]"

$out = @(
    '---', 'status: canonical', "last_reviewed: $(Get-Date -Format 'yyyy-MM-dd')", 'scope: ecosystem', '---', '',
    '# Case Registry (summarized wikilink index)', '',
    $intro, '', $hub, ''
)

foreach ($key in $groups.Keys) {
    $items = $groups[$key]
    if ($items.Count -eq 0) { continue }
    $out += "## $($titles[$key])"
    $out += ''
    $out += '| Case | Status | Updated | Summary |'
    $out += '|------|--------|---------|---------|'
    foreach ($c in ($items | Sort-Object Slug)) {
        $line = '| [[' + $c.Slug + ']] | ' + (Format-Status $c.Status) + ' | ' + $c.Updated + ' | ' + $c.Summary + ' |'
        $out += $line
    }
    $out += ''
}

$registryPath = Join-Path $casesDir "CASE_REGISTRY.md"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($registryPath, ($out -join "`n") + "`n", $utf8NoBom)
Write-Host "Updated $registryPath ($total cases: $complete complete, $active active/blocked)"
if (-not $SkipFrontmatter) {
    Write-Host "Frontmatter projection: $fmChanged changed, $fmUnchanged unchanged, $fmSkipped skipped (non-case)."
}
